---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - n8n.n8n.io
  resources:
  - n8ncredentials
  - n8nworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - n8n.n8n.io
  resources:
  - n8ncredentials/finalizers
  - n8nworkflows/finalizers
  verbs:
  - update
- apiGroups:
  - n8n.n8n.io
  resources:
  - n8ncredentials/status
  - n8nworkflows/status
  verbs:
  - get
  - patch
  - update
